name: pick_departure_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get_it: ^7.6.4
  go_router: ^12.1.3
  lottie: ^2.7.0
  sqflite: ^2.3.0
  intl: ^0.19.0
  barcode_widget: ^2.0.4
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  cloud_firestore: ^4.14.0
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21